// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb3TRZ8vF91eZbeCMBVP-jWxgYLVlzlPA',
    appId: '1:679766170563:web:710363eb9e7b28284bfb76',
    messagingSenderId: '679766170563',
    projectId: 'fir-auth-23ffc',
    authDomain: 'fir-auth-23ffc.firebaseapp.com',
    storageBucket: 'fir-auth-23ffc.appspot.com',
    measurementId: 'G-T365WMWGJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV6Jt4kDWC2unwGpUumAbp-MApRBlge6s',
    appId: '1:679766170563:android:b880fe1cb81f32644bfb76',
    messagingSenderId: '679766170563',
    projectId: 'fir-auth-23ffc',
    storageBucket: 'fir-auth-23ffc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnvmS_HaK75XyllYA3PfCSWgqsORPAWgg',
    appId: '1:679766170563:ios:e17e3b2ebaf569054bfb76',
    messagingSenderId: '679766170563',
    projectId: 'fir-auth-23ffc',
    storageBucket: 'fir-auth-23ffc.appspot.com',
    iosBundleId: 'com.example.testapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnvmS_HaK75XyllYA3PfCSWgqsORPAWgg',
    appId: '1:679766170563:ios:167f026425f9d4bc4bfb76',
    messagingSenderId: '679766170563',
    projectId: 'fir-auth-23ffc',
    storageBucket: 'fir-auth-23ffc.appspot.com',
    iosBundleId: 'com.example.testapp1.RunnerTests',
  );
}
